/**
 * Barrel export para tipos de documentos
 * Re-exporta todos os tipos do domain.ts para compatibilidade
 */

export type {
  Value,
  Documento,
  CriarDocumentoParams,
  AtualizarDocumentoParams,
  ListarDocumentosParams,
  DocumentoComUsuario,
  Arquivo,
  ArquivoComUsuario,
  CriarArquivoParams,
  AtualizarArquivoParams,
  ListarArquivosParams,
  ItemDocumento,
  Pasta,
  CriarPastaParams,
  AtualizarPastaParams,
  PastaComContadores,
  PastaHierarquia,
  DocumentoCompartilhado,
  CompartilharDocumentoParams,
  DocumentoCompartilhadoComUsuario,
  ListarCompartilhamentosParams,
  Template,
  CriarTemplateParams,
  AtualizarTemplateParams,
  TemplateComUsuario,
  ListarTemplatesParams,
  DocumentoUpload,
  UploadArquivoParams,
  DocumentoUploadComInfo,
  ListarUploadsParams,
  DocumentoVersao,
  CriarVersaoParams,
  DocumentoVersaoComUsuario,
  ListarVersoesParams,
  SalaChat,
  CriarSalaChatParams,
  SalaChatComInfo,
  ListarSalasChatParams,
  MensagemChat,
  CriarMensagemChatParams,
  AtualizarMensagemChatParams,
  MensagemChatComUsuario,
  ListarMensagensChatParams,
  PresencaUsuario,
  EventoColaboracao,
  AutoSavePayload,
  ApiSuccessResponse,
  ApiErrorResponse,
  PaginatedResponse,
} from './domain';

export {
  PERMISSOES,
  TIPOS_PASTA,
  TIPOS_MEDIA,
  VISIBILIDADE_TEMPLATE,
  PERMISSAO_VALUES,
  TIPOS_ARQUIVO,
  EXTENSOES_PERMITIDAS,
  documentoSchema,
  criarDocumentoSchema,
  atualizarDocumentoSchema,
  pastaSchema,
  criarPastaSchema,
  atualizarPastaSchema,
  compartilhamentoSchema,
  criarCompartilhamentoSchema,
  atualizarPermissaoCompartilhamentoSchema,
  templateSchema,
  criarTemplateSchema,
  atualizarTemplateSchema,
  uploadSchema,
  criarUploadSchema,
  autoSavePayloadSchema,
  criarVersaoSchema,
  criarSalaChatSchema,
  criarMensagemChatSchema,
  atualizarMensagemChatSchema,
  arquivoSchema,
  criarArquivoSchema,
  atualizarArquivoSchema,
} from './domain';

